### ISSUE TITLE
connecting mocks to spectra: outstanding issues

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#169]
PR #156 merged the first version of the code which connects mock catalogs to spectra (and the corresponding target and truth catalogs).  However, there were a number of outstanding issues (in no particular order):

- [X] Track down why no standard stars are being selected and written out.  *Comment* This bug was identified and fixed before #156 was merged.

- [X] Include velocity dispersion broadening in the galaxy spectra.  *Comment* After the speed-up to `desisim.templates` in https://github.com/desihub/desisim/pull/229 velocity dispersion broadening is now being included.

- [ ] Add contaminants to all the spectral classes.

- [ ] Validate the space-densities of the targets after target selection.  *Comment* We need some QA to ensure that the targeting criteria being applied in `desitarget.mock.selection` are correct, and that the resulting target catalogs have the right space-density.

- [ ] Add some basic unit tests.

- [ ] Resolve desihub/desisim#228 about lya_spectra not being generated at the correct redshift due to `z_wind` logic

- [X] file format fixes (fixed in PR #170)

- [ ] #159 : parallelize `select_mock_targets`

- [ ] Add shapes and sizes to the target catalogs.  *Comment*: Since morphology isn't going to be used for the 2% sprint (and possibly even the 20% challenge) this could be de-prioritized.

I'm certain I'm missing other issues so let's expand this list.

**Comment by moustakas** [comment]
@sbailey and @forero have independently reported (off-list) a problem with generating the mock spectra with the current version of the code.  I've been able to reproduce the problem on edison with the setup and commands below.


```bash
source /project/projectdirs/desi/software/desi_environment.sh
module swap desiutil/1.9.3
module swap desispec/0.13.2
module swap desisim/master
module swap desitarget/master

mkdir -p $SCRATCH/datachallenge2017 && cd $SCRATCH/datachallenge2017
cp -i /scratch1/scratchdirs/ioannis/datachallenge2017/mock_input_newtest.yaml .

srun -N 1 -n 1 -c 24 -p debug -L SCRATCH,project \
time select_mock_targets -c mock_input_newtest.yaml -s 444 --nproc 24 --output_dir newtest
```

For the record the problem seems to be when the ELG spectra are generated, so it's perhaps related to the `desisim.templates` speed-up, but I'm looking into it.  Here are the last few lines of the log output:
```
[snip]
INFO:io.py:129:load_all_mocks: Loaded 9 mock catalog(s).

INFO:build.py:530:targets_truth: Assigned 18480 MWS_MAIN objects to 180 unique 0.25x0.25 deg2 bricks.
INFO:build.py:537:_update_spectra_status: 10 bricks; 0.7 sec / brick
INFO:build.py:537:_update_spectra_status: 20 bricks; 0.4 sec / brick
INFO:build.py:537:_update_spectra_status: 30 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 40 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 50 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 60 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 70 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 80 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 90 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 100 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 110 bricks; 0.3 sec / brick
INFO:build.py:537:_update_spectra_status: 120 bricks; 0.2 sec / brick
INFO:build.py:537:_update_spectra_status: 130 bricks; 0.2 sec / brick
INFO:build.py:537:_update_spectra_status: 140 bricks; 0.2 sec / brick
INFO:build.py:537:_update_spectra_status: 150 bricks; 0.2 sec / brick
INFO:build.py:537:_update_spectra_status: 160 bricks; 0.2 sec / brick
INFO:build.py:537:_update_spectra_status: 170 bricks; 0.2 sec / brick
INFO:build.py:578:targets_truth: Downsampling to desired target density 200.0 targets/deg2.

INFO:build.py:530:targets_truth: Assigned 46615 ELG objects to 181 unique 0.25x0.25 deg2 bricks.
srun: error: nid05457: task 0: Killed
srun: Terminating job step 4693735.0
srun: Force Terminated job step 4693735.0
```

**Comment by moustakas** [comment]
This crash/problem was indeed due to the velocity dispersion caching implemented in https://github.com/desihub/desisim/pull/229.  Previously, the sparse convolution matrix was being computed on-the-fly for each simulated (galaxy) spectrum, which was *very* slow.  This issue was addressed by pre-computing the matrices for a much smaller subset of unique velocity dispersion values (specifically, 40 values or 10% of the number of model spectra being simulated, whichever was smaller).  

However, the node runs out of memory (as does my laptop!) when using multiprocessing to generate spectra with 24 cores simultaneously.  I should have worked this out ahead of time, but roughly:  each spectrum is ~40,000 pixels, so the matrix is 40000x40000 times, say, 40 unique values, times 24 cores.  And I just realized that the matrix was being stored in double precision.  Yikes.  

In general, `desisim.templates` could use a careful assessment of memory usage (for example, the spectra themselves are all double precision), although this is outside the scope of the current effort.  As a minimal change I force the sparse matrix to be single precision (see https://github.com/desihub/desisim/pull/231) and will open another ticket for a possible bigger cleanup.

However, for the 2% sprint I propose (and @dkirkby concurs) that we just leave off velocity dispersion broadening and solve this memory problem in the coming weeks (because we will definitely want smoothed spectra for the 20% sample).

**Comment by moustakas** [comment]
Assuming the `desisim` and `desitarget` modules at NERSC have been updated to master (including https://github.com/desihub/desisim/pull/231 and https://github.com/desihub/desitarget/pull/171) then this script (which excludes velocity broadening) should create 10 deg2 of data in ~23 min with 24 cores on edison.

```bash
source /project/projectdirs/desi/software/desi_environment.sh
module swap desiutil/1.9.3
module swap desispec/0.13.2
module swap desisim/master
module swap desitarget/master

mkdir -p $SCRATCH/datachallenge2017 && cd $SCRATCH/datachallenge2017
cp -i /scratch1/scratchdirs/ioannis/datachallenge2017/mock_input_newtest.yaml .

srun -N 1 -n 1 -c 24 -p debug -L SCRATCH,project \
time select_mock_targets -c mock_input_newtest.yaml -s 444 --nproc 24 --output_dir newtest
```

My version of the resulting output files (with permissions hopefully set correctly!) are in
`/scratch1/scratchdirs/ioannis/datachallenge2017/newtest` 
[5.5GB]

@sbailey @forero let me know if you identify any other issues.

**Comment by forero** [comment]
great. I will launch again the 2% mock_target_selection and let you all know whether new issues pop up.

**Comment by dkirkby** [comment]
Thanks @moustakas!

@forero How are you ensuring that your generated targets cover the 2% footprint, which isn't very tight:
![twopct](https://cloud.githubusercontent.com/assets/185007/24809509/9198de92-1b74-11e7-94c1-8478043bebcf.png)

**Comment by forero** [comment]
@dkirkby I am splitting the sky in 2x2 degrees "boxes" (in ra, dec) and generating the mocks only for those boxes with some observed tile in it.

https://github.com/desihub/two_percent_DESI/blob/master/sprint.py#L19-L26

**Comment by dkirkby** [comment]
Since you are binning the tile centers, you might miss some of the tile area at the edges of the footprint.  A simple fix would be to bin (ra0+/-dra, dec0+/-ddec) [4 points] in addition to the tile centers (ra0,dec0).

**Comment by forero** [comment]
Right @dkirkby. I've now included additional points around the tile center.

**Comment by moustakas** [comment]
With #173 now merged here's my assessment of the complete and outstanding issues with the connection between mocks and spectra.  None of the outstanding issues should hold up the 2% sprint (assuming we can complete it without memory or wall clock problems!) and can be tackled ahead of the 20% challenge (or later).

**Complete:**
- [X] Fix bug where no standard stars are being written out.  Fixed in #156.

- [X] Fix bug where Lya spectra are not being generated at the correct redshift.  Fixed in desihub/desisim#228.

- [X] Fix file format issues.  Fixed in #170.

- [X] Parallelize `select_mock_targets` (see #159).  @forero has a basic infrastructure working now but we can revisit this later if necessary.

- [X] Add shapes and sizes to the target catalogs. Added in #173 for ELGs and LRGs but not yet for BGS (see below).

- [X] Add contaminants to all the spectral classes. A flexible code infrastructure for doing this was added in #173 but it needs to be tuned (see below).

**Outstanding:**

- [ ] Add some basic unit tests.

- [ ] Include velocity dispersion broadening in the galaxy spectra. Velocity broadening is still a memory hog that we (I) thought was fixed in https://github.com/desihub/desisim/pull/229 but alas.

- [ ] The space-densities of the final target lists (true targets as well as contaminants) are not correct in detail (for different reasons depending on the target).  I have *started* looking into this in [this notebook](https://github.com/desihub/desitarget/blob/master/doc/nb/mock-qa.ipynb).

- [ ] Related to the previous bullet, we need input from the Targeting WG about contaminants. For example, will BGS targets be contaminants for any other target class? What fraction of BGS targets do we expect to be stars?  How many stellar/extragalactic contaminants do we expect for LRGs? Finally, the SKY targets appear to be consistently below the 1400/deg2 desired target density.

- [ ] The code generates a large number of templates/spectra in order to compute the colors correctly but then throws many/most of them away after applying color cuts (this is especially true for the FAINTSTAR and ELG classes).  This is wasteful, inefficient, and doesn't scale!

- [ ] Related to the previous point, the Gaussian Mixture Models (GMMs) for the ELGs, LRGs, and QSOs need to be deconvolved for photometric scatter (or calibrated in regions with deeper-than-average imaging).  Also, the GMMs are missing the `FRACDEV` parameter.

- [ ] The MWS stars are assigned templates based on their gridded Teff/logg/[Fe/H] values but we should really should be interpolating.

- [ ] For speed and convenience the Lya forest spectra for the QSOs are being computed on-the-fly (see https://github.com/desihub/desisim/pull/234), but these lack the BAO signal we need/want.  We need to revert back to using the on-disk Lyman-alpha skewers/mocks.

- [ ] White dwarf standard stars are being selected but not written out. This is trivial to add but was left off to not break the MTL code for the 2% sprint.

- [ ] We need to validate that we can use the `MOCKID` in the output target catalog to get back to the correct row in the original mock catalog (this is related to #88).

Anything else?

**Comment by dkirkby** [comment]
This is really useful, thanks.

> Also, the GMMs are missing the FRACDEV parameter.

I think this was just an oversight and I know @belaa is aware of this.

**Comment by dkirkby** [comment]
I just linked your checklist to https://github.com/desihub/two_percent_DESI/blob/master/progress.md

**Comment by apcooper** [comment]
>  White dwarf standard stars are being selected but not written out. This is trivial to add but was left off to not break the MTL code for the 2% sprint.

Is this fixed now?

**Comment by moustakas** [comment]
Yes, white dwarfs are being written out as (bright- and dark-time) standards:
https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/build.py#L845-L847

**Comment by apcooper** [comment]
Thanks. It's right for STD_WD to be used in bright and dark time, but this looks inconsistent with https://github.com/desihub/desitarget/blob/master/py/desitarget/data/targetmask.yaml#L24, where the obsconditions for STD_WD are 0DARK|GRAY)... this is potentially confusing?

**Comment by moustakas** [comment]
Good catch.  Can you open a new issue (or fix this in a PR)?  I'm fairly certain it was decided at the June collaboration meeting that white dwarfs would be observed at highest priority in *all* sky conditions.

**Comment by geordie666** [comment]
For the record, I'm definitely in favor of WDs being observed at highest priority in all sky conditions. If anyone strongly disagrees, they should push back in this thread.

**Comment by moustakas** [comment]
I've moved most of the remaining outstanding issues to #252 so I'm closing this.
