### ISSUE TITLE
select_mock_targets -- desired updated features and bug fixes

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#252]
Current high-priority punch list.

- [ ] Ensure all targets -- including contaminants -- have the correct / desired target density (see #192 for QSOs).

- [ ] Use simqso to generate QSO spectra with the correct underlying QSO luminosity function (see https://github.com/desihub/desisim/pull/293)

- [ ] The MWS photometry written out in the truth catalog may have an indexing bug (see #251).

- [ ] Fix duplicate TARGETIDs (#178).

- [ ] Add units to target and truth files (#237).

- [ ] Validate we can use the `MOCKID` in the output target catalog to get back to the correct row in the original mock catalog (#88).

- [ ] Use GMMs based on DR5 and deconvolved for photometric scatter (see #250).

- [ ] Compare columns in mock and data target catalogs and assess (related to #209). For example, I've already added `PSFDEPTH_[W1,W2]` to the mock target catalog.

**Comment by moustakas** [comment]
Most of these issues were addressed in #264, @sbailey has opened new outstanding issues, and I'll open some more.  Closing this for now.
