### ISSUE TITLE
Update mocks to make new footprints easier

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#390]
Update our suite of mocks to make it easier to re-use them for different footprints, e.g. the updated dithering in https://desi.lbl.gov/trac/browser/code/desimodel/branches/newtiles/data/footprint/ or the upcoming update to match the final imaging footprint.

Suggestion from @schlafly: generate mocks for a superset of what we might possibly ever include, e.g. dec>-20 and |b|>10.  After that, I see two basic options:

1. provide simple code to trim the bigger mocks into mocks matched to a particular tiling.  This is similar to our current mocks whose footprint is tuned to a particular tiling, and is convenient for stuff like `efficiency = num_targets_in_zcatalog / num_targets_in_mock`.
2. always use the superset, and leave it to the final analyses to make edge corrections for the particular tiling used.

I prefer (2) because then we don't have to maintain unique versions of mocks for unique tilings, and because you'll need to do something like that when using a mock to evaluate DESI part way through the survey anyway.

Mocks currently in use by the end-to-end tests, starting from `/project/projectdirs/desi/mocks/`:
* [ ] bgs/MXXL/desi_footprint/v0.0.4/BGS.hdf5
* [ ] GaussianRandomField/v0.0.8_2LPT/ELG.fits
* [ ] GaussianRandomField/v0.0.8_2LPT/LRG.fits
* [ ] GaussianRandomField/v0.0.8_2LPT/QSO.fits
* [ ] lya_forest/london/v2.0/master.fits
* [ ] mws/galaxia/alpha/v0.0.5/healpix
* [ ] mws/100pc/v0.0.3/mock_100pc.fits
* [ ] mws/wd/v0.0.2/mock_wd.fits
* [ ] uniformsky/0.1/uniformsky-2048-0.1.fits

@moustakas and/or @forero can you shepherd this through?

Useful code:
  * `desimodel.footprint.tiles2pix` (tiles table -> healpixels covering those tiles)
  * `desimodel.footprint.is_point_in_desi` (tiles table + ra,dec arrays -> yes/no)

**Comment by sbailey** [comment]
Mostly history.  I grabbed the list that are the current defaults in desitarget/doc/mock_example/input.yaml .  I don't know whether the current mock making code makes use of the `E1` and `E2` columns in the default mocks but which aren't present in the Dark Sky mocks (probably not).

It looks like the Dark Sky mocks already have the concept of superset (*_inpt.fits) and footprint trimmed versions (*_desi.fits), so updating them is presumably a simple operations of cutting a new version and making a different trimming, or just defaulting to using the untrimmed.

**Comment by moustakas** [comment]
Note:  Boris Gaensicke has updated the MWS/WD mock (all-sky) to include Gaia/DR2 quantities--
  /project/projectdirs/desi/mocks/mws/wd/v1.0.0

**Comment by moustakas** [comment]
Updating the list of mocks given the latest defaults adopted in #395 and adding some notes:

* [x] bgs/MXXL/desi_footprint/v0.0.4/BGS.hdf5 -- **Alex Smith has provided an all-sky version in bgs/MXXL/full_sky/v0.0.4/BGS_r20.6.hdf5 which can become our new default.**
* [x] DarkSky/v1.0.1/elg_0_inpt.fits, lrg_0_inpt.fits, qso_0_inpt.fits -- **See below.**
* [x] lya_forest/london/v4.0/master.fits -- **All-sky.**
* [ ] mws/galaxia/alpha/v0.0.6/healpix -- **Being discussed in #352.**
* [ ] mws/100pc/v0.0.3/mock_100pc.fits -- **All-sky but needs to be updated with Gaia (maybe as part of #352).  @apcooper?**
* [x] mws/wd/v1.0.0/mock_wd.fits -- **All-sky.**
* [x] uniformsky/0.1/uniformsky-2048-0.1.fits -- **Done in #398.**

* [ ] GaussianRandomField/v0.0.8_2LPT/ELG.fits, LRG.fits, QSO.fits -- **No updates but perhaps we should fully deprecate these in favor of DarkSky?**

Regarding the DarkSky mocks, can we convince ourselves that they don't need to be updated? The screenshot below shows the current mock footprint (v1.0.1, blue) and the current DESI (healpixelized) footprint (old tile file, orange).  By zooming into various edges I think I've convinced myself there's enough of a border (especially in the NGC) for this catalog to be sufficient, but maybe someone should double-check me.

![junk](https://user-images.githubusercontent.com/1431820/46806431-96b1de00-cd35-11e8-8e72-0f014d6a96df.png)

**Comment by apcooper** [comment]
Just a note to say I'm working on the MWS mocks for a footprint |b| > 10, dec > -30.  Re. #352, these will have Gaia columns in the regular version but no velocity info at all in the superfaint version to keep the size down.

I'll post here when they're done.

**Comment by apcooper** [comment]
New MWS mocks (v0.0.6 and v0.0.6_superfaint) are up at NERSC. These include all NSIDE=8 healpix that have any overlap with the area dec > -30, |b| > 10. As #352, for the standard mocks the Galaxia and Gaia columns are combined into one file; the superfaint mocks don't include any Gaia columns.

**Comment by moustakas** [comment]
Thanks @apcooper!  I'll take a look today.

Any thoughts on an updated `mock_100pc.fits` catalog?

**Comment by apcooper** [comment]
@moustakas, can you remind me what exactly needs updating in the 100pc mock? Is it just renaming the columns to match the Galaxia mock (and adding units), or are some extra columns needed?

The 100pc mock comes from the GUMS model (not the Galaxia run used for the other mocks) so I think the columns in there already refer to Gaia measurements.

**Comment by apcooper** [comment]
I've updated the 100pc mock file with remapped column names and associated units to those.

```
 'RA',
 'DEC',
 'PMRA',
 'PMDEC',
 'TRUE_RADIAL_VELOCITY',
 'TRUE_DHELIO',
 'TRUE_TEFF',
 'TRUE_LOGG',
 'TRUE_AGE',
 'TRUE_FEH',
 'TRUE_MASS',
 'TRUE_TYPE',
 'TRUE_MBOL',
 'GAIA_PHOT_G_MEAN_MAG',
 'GAIA_PHOT_BP_MEAN_MAG',
 'GAIA_PHOT_RP_MEAN_MAG',
 'TRUE_WD',
 'BRCKNAME',
 'BICKID',
 'OBJID',
 'IPIX8'
```

> Which column refers to the parallax, or do I need to derive that from the distance? In addition, there doesn't seem to be an error model, which we need to select the 100 pc sample:

At the moment we're not set up to model the (probably fairly small) effect of parallax errors in selecting the NEARBY sample from the full Gaia catalog. We're treating the 100pc mock (in whch each star is taken from GUMS by distance, not parallax) as the end result of the selection, _after_ the data quality and parallax cuts have been applied. All stars in the mock (in the G mag range) should be included in the target selection. There is no contamination from any other sample. 

I recall that, somewhere under `select_mock_targets`, we're removing any stars with  `d < 100pc` by hand from the Galaxia mock, to avoid double counting.

I guess we could put in the error columns (from GUMS rather than PyGaia, I guess) and do the selection more realistically, but we should get Boris' opinion on that.

**Comment by apcooper** [comment]
@moustakas, I've noticed a small bug in the 0.0.6 mocks -- there are columns `"OBJID"` and `"objid"`, with different values. I'll let you know when this is fixed.

**Comment by moustakas** [comment]
> At the moment we're not set up to model the (probably fairly small) effect of parallax errors in selecting the NEARBY sample from the full Gaia catalog. We're treating the 100pc mock (in whch each star is taken from GUMS by distance, not parallax) as the end result of the selection, after the data quality and parallax cuts have been applied. All stars in the mock (in the G mag range) should be included in the target selection. There is no contamination from any other sample.

So parallax error should be removed from the selection criteria for the `MWS_NEARBY` sample, right?
https://desi.lbl.gov/trac/wiki/TargetSelectionWG/TargetSelection#a100pcvolume-limitedsurveyMWS-NEARBY

Also, although there's no parallax error in this mock (which is fine---I'll just set the ivar to something big), I would still like to propagate it into the (mock) target catalog (for QA, etc.).  Can you include an estimate of the parallax for each target even though every object should pass the selection cuts?

> I recall that, somewhere under select_mock_targets, we're removing any stars with d < 100pc by hand from the Galaxia mock, to avoid double counting.

Correct, any `MWS_MAIN/Galaxia` object that gets selected as a `MWS_NEARBY` target is removed, to not double-count when selecting `d<100 pc` targets from the `MWS_NEARBY` mock.

> I've noticed a small bug in the 0.0.6 mocks -- there are columns "OBJID" and "objid", with different values. I'll let you know when this is fixed.

No rush on my end.

**Comment by apcooper** [comment]
> At the moment we're not set up to model the (probably fairly small) effect of parallax errors in selecting the NEARBY sample from the full Gaia catalog. 

> So parallax error should be removed from the selection criteria for the MWS_NEARBY sample, right?

Sorry, I didn't say this clearly. We _are_ set up to do this with the real Gaia data, just not with the mock. The criteria on the TS page are ok, that's what we want to use.

As far as I can see, the only thing blocking doing the parallax selection with the mock is that we didn't propagate that column from GUMS. If we did, we'd have to think again about how to handle the overlap with the Galaxia mock, but I don't think that's a big deal. I'll let Boris know about this discussion.

> Can you include an estimate of the parallax for each target even though every object should pass the selection cuts?

I've added a `PARALLAX` column, which is just `1/TRUE_DHELIO`, no error model. I've checked all the stars have `PARALLAX > 10 mas`.

> No rush on my end.

It's fixed now, anyway.

**Comment by moustakas** [comment]
> New MWS mocks (v0.0.6 and v0.0.6_superfaint) are up at NERSC. These include all NSIDE=8 healpix that have any overlap with the area dec > -30, |b| > 10. As #352, for the standard mocks the Galaxia and Gaia columns are combined into one file; the superfaint mocks don't include any Gaia columns.

One consequence of the generous, updated footprint is that the Galaxia/MWS mock is now `224GB` vs `36GB` previously.  This increase is to be expected since we've pushed into the Galactic plane, but it does mean that the mock catalog no longer fits on my laptop!

**Comment by apcooper** [comment]
Yes.

It's straightforward to spot the healpix that contribute most to the increase (obviously those towards the bulge and in the plane). If those healpix were safely outside the current footprint perhaps they could just be left out of a laptop copy. I can see that being even more important for the superfaint mock.

If someone could make a list of the subset of files required for a 'lite' version based on a particular footprint maybe it would be useful to have that in the root of the mock directory (i.e. a list of paths for use with rsync)?

ps. for a given healpix, I think the new mock should be smaller than the old one, allowing for the old one being split into two files per healpix.

**Comment by moustakas** [comment]
Other than my [question](https://github.com/desihub/desitarget/issues/390#issuecomment-428951883) about the DarkSky footprint (which I don't think should prevent us from closing this issue), here is the updated set of mocks implemented in #424:

* [x] bgs/MXXL/full_sky/v0.0.4/BGS_r20.6.hdf5 -- **All-sky**
* [x] DarkSky/v1.0.1/elg_0_inpt.fits, lrg_0_inpt.fits, qso_0_inpt.fits -- **Probably OK but see [here](https://github.com/desihub/desitarget/issues/390#issuecomment-428951883).**
* [x] lya_forest/london/v4.0/master.fits -- **All-sky**
* [x] mws/galaxia/alpha/v0.0.6/healpix -- **Expanded footprint implemented in #352.**
* [x] mws/100pc/v0.0.4/mock_100pc.fits -- **All-sky**
* [x] mws/wd/v1.0.0/mock_wd.fits -- **All-sky**
* [x] uniformsky/0.2/uniformsky-2048-0.2.fits -- **All-sky implemented in #398.**

Also note that the Gaussian random field mocks have been deprecated in favor of the DarkSky mocks.

**Comment by moustakas** [comment]
Done in #424.
